### ISSUE TITLE
github corner covers menu-button on mobile view

### ISSUE THREAD

**Issue by setempler** [nandomoreirame/end2end#16]
Hi,

many thanks for providing the theme (see in action: www.templer.se).

I needed to drop the 'github-corner' from `source/_layouts/default.html` to not cover the menu button that appears instead of the site links in the header when viewing with Safari from iOS. On home it does not matter.

Regards,
Sven

**Comment by keeratsingh** [comment]
Created pull request #27

**Comment by nandomoreirame** [comment]
Pull request accepted, thanks for your contribution @keeratsingh
