### ISSUE TITLE
Unable to publish the page online

### ISSUE THREAD

**Issue by raghav-coding** [nandomoreirame/end2end#20]
Hello,

I used your theme. This is my repository: https://github.com/raghavgujjar/raghavgujjar.github.io.
But, unable to see it even though I customized and pushed the changes: http://raghavgujjar.github.io/.
What am I missing? I'm unfamiliar with Ruby. Can you help please?

**Comment by raghav-coding** [comment]
Still having build issues. Created gh-pages. https://github.com/raghavgujjar/raghavgujjar.github.io

**Comment by nandomoreirame** [comment]
I'm sorry guys!
This link now > http://github.nandomoreira.me/end2end
