### ISSUE TITLE
Long Strings or URLs break CSS Layout

### ISSUE THREAD

**Issue by keeratsingh** [nandomoreirame/end2end#25]
Long string or URLs break the CSS layout as seen in the screenshot below.

![url_bug_desktop](https://cloud.githubusercontent.com/assets/2684055/17645048/cfe20a6a-614e-11e6-8568-f1379f8d0e67.jpg)
![url_bug_desktop2](https://cloud.githubusercontent.com/assets/2684055/17645047/cfdfbf58-614e-11e6-8339-fce69f969f43.jpg)

**Comment by keeratsingh** [comment]
Created pull request #26

**Comment by nandomoreirame** [comment]
Pull request accepted, thanks for your contribution @keeratsingh  :)
