### ISSUE TITLE
Rake deploy Acting Up

### ISSUE THREAD

**Issue by NoahVlncrt** [nandomoreirame/end2end#3]
When I rake deploy for every link it generates 2 '/' instead of one which is causing a bunch of problems any idea what that is?

**Comment by NoahVlncrt** [comment]
Nevermind I have solved the problem. In my config file I had base url set as "/" which was causing problems and breaking links.

**Comment by nandomoreirame** [comment]
Thank you for using my project @NoahVlncrt ;)

**Comment by NoahVlncrt** [comment]
@nandomoreirame No problem I love this template. If you wouldn't mind you should check out your pull requests on this repo. I've fixed something that would be beneficial to everyone else.
