### ISSUE TITLE
Bourbon for Ruby on Rails 4.2+

### ISSUE THREAD

**Issue by iamlordaubrey** [nandomoreirame/end2end#37]
In the readme, the command `bundle exec jekyll serve` fails for Ruby on Rails 4.2+.
`@import "bourbon/bourbon"` is the culprit. 

Using `@import "bourbon"` fixes this... as can be seen [here](https://github.com/thoughtbot/bourbon#installation-for-ruby-on-rails-42)

It's a small one, so I didn't think to create a PR. I could should you wish :)

**Comment by caseyprovost** [comment]
This is already done in `source/_sass/main.sass` it appears. 👀  cc @ nandomoreirame

**Comment by nandomoreirame** [comment]
yes, it is done. thanks.
