### ISSUE TITLE
Rake failed with Permission denied

### ISSUE THREAD

**Issue by thanhnguyentang** [nandomoreirame/end2end#4]
Hi @nandomoreirame, I really love your theme and want to adapt this for my blog. However, the installation didn't  go easily.  I follow [these instructions](https://github.com/nandomoreirame/end2end) but had a problem with  the following commands:  

> > Deploy in Github pages in 2 steps
> > 
> > Change the variables GITHUB_REPONAME and GITHUB_REPO_BRANCH in Rakefile
> > Run rake or rake publish for build and publish on Github  

It throws the following error:  
![end2end-error](https://cloud.githubusercontent.com/assets/13204600/12372888/72ec6f62-bc99-11e5-9d00-0b8ebdbeb94c.png)

Would you mind helping me out for this? :)

**Comment by nandomoreirame** [comment]
I do not see your repository, Where is it?

**Comment by nandomoreirame** [comment]
you need to change the line 8 `Rakefile` with your repository

https://github.com/nandomoreirame/end2end/blob/master/Rakefile#L8

e.g `thanh-ng/end2end`

**Comment by nandomoreirame** [comment]
you are trying to send to my repository `nandomoreirame/end2end`, so it is giving the error: Permission denied

**Comment by thanhnguyentang** [comment]
Here it is: https://github.com/thanh-ng/thanh-ng.github.io

**Comment by thanhnguyentang** [comment]
It did change it but it seems that still it does not work.

**Comment by nandomoreirame** [comment]
ah yes, I found the error.

You are trying to push to master.

try to push gh-pages

https://github.com/thanh-ng/thanh-ng.github.io/blob/master/Rakefile#L9

**Comment by thanhnguyentang** [comment]
I tried that too but it gave the same error as in the screenshot :(

**Comment by thanhnguyentang** [comment]
I fixed it anyway. Thanks for an nice theme :)

**Comment by witwiki** [comment]
Hey @thanh-ng 

I am having the same issue. Could you please put here how you fixed the issue?

Thanks in advance

**Comment by witwiki** [comment]
@thanh-ng   and @nandomoreirame 

```
Configuration file: _config.yml
cp -r _site/. /tmp/d20161118-11690-18lbqs8
Initialized empty Git repository in /tmp/d20161118-11690-18lbqs8/.git/
Switched to a new branch 'gh-pages'
[gh-pages (root-commit) 84c36d5] Site updated at 2016-11-18 07:51:23 UTC
 22 files changed, 2078 insertions(+)
 create mode 100644 404.html
 create mode 100644 about/index.html
 create mode 100644 blog/2015/a-wonderful-serenity-has-taken-possession-of-my-entire-soul/index.html
 create mode 100644 blog/2015/far-far-away-behind-the-word-mountains-far-from-the-countries-vokalia-and-consonantia/index.html
 create mode 100644 blog/2015/lorem-ipsum-dolor-sit-amet-consectetuer-adipiscing-elit/index.html
 create mode 100644 blog/2015/lorem-ipsum-dolor-sit/index.html
 create mode 100644 blog/2015/lorem/index.html
 create mode 100644 blog/2015/the-quick-brown-fox-jumps-over-a-lazy-dog/index.html
 create mode 100644 blog/2015/welcome-to-jekyll/index.html
 create mode 100644 blog/index.html
 create mode 100644 blog/page/2/index.html
 create mode 100644 blog/page/3/index.html
 create mode 100644 css/main.css
 create mode 100644 feed.xml
 create mode 100644 fonts/end2end-icons.eot
 create mode 100644 fonts/end2end-icons.svg
 create mode 100644 fonts/end2end-icons.ttf
 create mode 100644 fonts/end2end-icons.woff
 create mode 100755 images/author.jpg
 create mode 100644 images/bg-pattern.png
 create mode 100644 index.html
 create mode 100644 resume/index.html
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

I get the same **Permission denied (publickey)** error...

Any help would be **_much_** appreciated...

**Comment by lucasrodes** [comment]
Same issue here. I think this thread was not properly closed ^_^

Thanks in advance!

**Comment by pawanline** [comment]
@thanhnguyentang @nandomoreirame  How do we fixed this guys. I am getting the same.

**Comment by pawanline** [comment]
@lucasrodes How are you cloning the repo? I was cloning using https.if It is so please clone using ssh . 
It solved my issue thanks @nandomoreirame for helping me out .

**Comment by MuhammadHasham23** [comment]
Same issue. @nandomoreirame permission is denied despite changing the push origin.
