### ISSUE TITLE
Github page doesn't exist when deploying

### ISSUE THREAD

**Issue by lpossamai** [nandomoreirame/end2end#47]
Hi.

I followed your steps, and when deploying to my repository I get: "There isn't a GitHub pages site here".
http://lpossamai.github.io

Steps that I made:

1. Downloaded the repository
2. Install Ruby gems
3. Start Jekyll server (This works fine)
4. Changed the variables `GITHUB_REPONAME` and `GITHUB_REPO_BRANCH` in `Rakefile`
5. Ran `rake`

Am I missing something? Cheers!

**Comment by nandomoreirame** [comment]
Remove baseurl /end2end

```yml
baseurl: "/end2end"
```

![image](https://user-images.githubusercontent.com/1318271/51771211-6bc67c80-20cf-11e9-867a-c0915fdc551f.png)

the file main.css (https://lpossamai.github.io/end2end/css/main.css) returns 404 error.
remove /end2end like this > https://lpossamai.github.io/css/main.css

on line 25 in the file `_config.yml`

https://github.com/nandomoreirame/end2end/blob/master/_config.yml#L25

**Comment by lpossamai** [comment]
Thanks for your prompt reply @nandomoreirame .

I've removed the "/end2end" as you suggested:

First I tried:
`baseurl: ""`

Then I tried to remove the entire line `baseurl: ""`.
But the problem persists.

ANy more tips? Obrigado! :)

**Comment by lpossamai** [comment]
I'm getting:
`Refused to load the font '<URL>' because it violates the following Content Security Policy directive: "default-src 'none'". Note that 'font-src' was not explicitly set, so 'default-src' is used as a fallback.`

Added to index.html (seen here https://github.com/phonegap/phonegap-app-desktop/issues/801):
`<meta http-equiv="Content-Security-Policy" content="default-src 'self' gap:; script-src * data: https://ssl.gstatic.com 'unsafe-inline' 'unsafe-eval'; object-src *; style-src 'self' data: 'unsafe-inline'; img-src 'self' data:; media-src 'self' data:; font-src 'self' data:; connect-src *">`

Did not fix the problem.

**Comment by lpossamai** [comment]
I just found out that the "CNAME" file is not there.

`https://lpossamai.github.io/` works!
`www.lpossamai.com` does NOT work.

How can I add that CNAME to my Jekyll installation? Do I need to commit the file ever time I run `rake`?

**Comment by lpossamai** [comment]
It seems to be working now. Thanks!
