### ISSUE TITLE
How to add a "CNAME" file?

### ISSUE THREAD

**Issue by lpossamai** [nandomoreirame/end2end#48]
Hi.

I have a custom domain and I cannot add it to my Jekyll installation.
`https://lpossamai.github.io/ `WORKS.

If I put a `CNAME` file in my repository, every time I run `rake` to deploy any changes, the file is gone.
How can I get this file uploaded to my repository?

If I manually commit the `CNAME` file, it works. But how can I add this to the `rake` command?

Thanks!

**Comment by lpossamai** [comment]
In the meantime, created a bash script so I can deploy without having to commit the `CNAME` file manually every time.

```
#!/bin/bash
# 
#
set -x

# Commit Jekyll changes through Rake
cd /home/lucas/Dropbox/bitbucket/lucas/lpossamai_Jekyll/
bundle exec rake

# Remove existing directory
rm -rf /home/lucas/Dropbox/bitbucket/lucas/lpossamai.github.io

# Close repository
cd /home/lucas/Dropbox/bitbucket/lucas/ && git clone git@github.com:lpossamai/lpossamai.github.io.git

# Commit the CNAME file and .gitignore
cp /home/lucas/Dropbox/bitbucket/lucas/lpossamai_Jekyll/CNAME /home/lucas/Dropbox/bitbucket/lucas/lpossamai.github.io/
cp /home/lucas/Dropbox/bitbucket/lucas/lpossamai_Jekyll/.gitignore /home/lucas/Dropbox/bitbucket/lucas/lpossamai.github.io/

cd /home/lucas/Dropbox/bitbucket/lucas/lpossamai.github.io/
git add .gitignore && git commit -m 'Adding .gitignore file'
git add CNAME && git commit -m 'Adding CNAME file for github pages www.lpossamai.com'
git push

exit 0
```

**Comment by Timothylock** [comment]
You can put the `CNAME` file in `./source/` and it will automatically commit the file

**Comment by SebGay** [comment]
@nandomoreirame First off, thanks for this great project. Do you have any sort of donation jar- I'd love to buy you a coffee!

Secondly, I've added CNAME to the source folder but `bundle exec rake publish` doesn't commit it and I have to manually do it on the repo page. Is there somewhere in the Rakefile that I need to track the file? After a poke around I'm more confused than ever.
